
import java.awt.Image;
import java.awt.print.PrinterException;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;



public class ventana extends javax.swing.JFrame {
    int crenglon =0;
    Creditos acerca;
    DefaultComboBoxModel tiposPizzas; 
    Icon icPepperoni, icHawaiana, icMexicana, icItaliana, ic4Quesos;
    
    public ventana() {
        initComponents();
        acerca = new Creditos(this, true);
        
        String pizzas[] = {"Pepperoni", "Hawaiana", "Mexicana", "Italiana", "4 Quesos"};
        tiposPizzas = new DefaultComboBoxModel(pizzas);
        combxTipo.setModel(tiposPizzas);
        rbChica.setSelected(true);
        lbl_fotoPizza.setSize(100,100);
        
        ImageIcon imgIcPep = new ImageIcon (getClass().getResource("pepperoni.jpg"));
        Image imgEscaladaPep = imgIcPep.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH); 
        icPepperoni = new ImageIcon(imgEscaladaPep);
        
        ImageIcon imgIcHw = new ImageIcon (getClass().getResource("hawaiana.png"));
        Image imgEscaladaHw = imgIcHw.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH); 
        icHawaiana = new ImageIcon(imgEscaladaHw);
        
        ImageIcon imgIcMx = new ImageIcon (getClass().getResource("mexicana.jpg"));
        Image imgEscaladaMx = imgIcMx.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH); 
        icMexicana = new ImageIcon(imgEscaladaMx);
        
        ImageIcon imgIcIta = new ImageIcon (getClass().getResource("italiana.png"));
        Image imgEscaladaIta = imgIcIta.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH); 
        icItaliana = new ImageIcon(imgEscaladaIta);
        
        ImageIcon imgIc4Q = new ImageIcon (getClass().getResource("4quesos.png"));
        Image imgEscalada4Q = imgIc4Q.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH); 
        ic4Quesos = new ImageIcon(imgEscalada4Q);
        
        lbl_fotoPizza.setIcon(icPepperoni);
        calcularPrecio();
    }

    public void calcularPrecio(){
        double total = 50;
        if(rbChica.isSelected()) total = total+10;
        if(rbMediana.isSelected()) total = total+20;
        if(rbGrande.isSelected()) total = total+30;
        if(rbJumbo.isSelected()) total = total+40; 
        generarNota();
        switch(combxTipo.getSelectedIndex()){
            case 0: total = total+5; break;
            case 1: total = total+10; break;
            case 2: total = total+25; break;
            case 3: total = total+15; break;
            case 4: total = total+20; break;
        }
        if(cbxQueso.isSelected()) total = total+15;
        if(cboxPina.isSelected()) total = total+15;
        if(cbxChampinones.isSelected()) total = total+20;
        if(cbxAceitunas.isSelected()) total = total+10;
        lblCosto.setText("Costo = "+total);
    }
    
    public void generarNota(){
        taNota.setText("Pizzeria \"EL POLLO\" \n\n");
        switch(combxTipo.getSelectedIndex()){
            case 0: taNota.append("Ha elegido pizza: PEPPERONNI"); break;
            case 1: taNota.append("Ha elegido pizza: HAWAIANA"); break;
            case 2: taNota.append("Ha elegido pizza: MEXICANA"); break;
            case 3: taNota.append("Ha elegido pizza: ITALIANA"); break;
            case 4: taNota.append("Ha elegido pizza: 4 QUESOS"); break;
        }
        
        if(rbChica.isSelected()) taNota.append("\nTamano chico");
        if(rbMediana.isSelected()) taNota.append("\nTamano mediano");
        if(rbGrande.isSelected()) taNota.append("\nTamano grande");
        if(rbJumbo.isSelected()) taNota.append("\nTamano jumbo");
        
        if(cbxQueso.isSelected()) taNota.append("\n- Queso extra");
        if(cboxPina.isSelected()) taNota.append("\n- Piña extra");
        if(cbxChampinones.isSelected()) taNota.append("\n- Champiñones extra");
        if(cbxAceitunas.isSelected()) taNota.append("\n- Aceitunas extra");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTamaños = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rbChica = new javax.swing.JRadioButton();
        rbMediana = new javax.swing.JRadioButton();
        rbGrande = new javax.swing.JRadioButton();
        rbJumbo = new javax.swing.JRadioButton();
        combxTipo = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        cbxQueso = new javax.swing.JCheckBox();
        cboxPina = new javax.swing.JCheckBox();
        cbxAceitunas = new javax.swing.JCheckBox();
        cbxChampinones = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taNota = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        lblCosto = new javax.swing.JLabel();
        lbl_fotoPizza = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabPedidos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        taNotaReconstruida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tamaño de la pizza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 204, 153));

        buttonGroupTamaños.add(rbChica);
        rbChica.setText("Chica");
        rbChica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickRadioBotonTamano(evt);
            }
        });

        buttonGroupTamaños.add(rbMediana);
        rbMediana.setText("Mediana");
        rbMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMedianaActionPerformed(evt);
                clickRadioBotonTamano(evt);
            }
        });

        buttonGroupTamaños.add(rbGrande);
        rbGrande.setText("Grande ");
        rbGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickRadioBotonTamano(evt);
            }
        });

        buttonGroupTamaños.add(rbJumbo);
        rbJumbo.setText("Jumbo");
        rbJumbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickRadioBotonTamano(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rbChica)
                .addGap(29, 29, 29)
                .addComponent(rbMediana)
                .addGap(18, 18, 18)
                .addComponent(rbGrande)
                .addGap(18, 18, 18)
                .addComponent(rbJumbo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbChica)
                    .addComponent(rbMediana)
                    .addComponent(rbGrande)
                    .addComponent(rbJumbo)))
        );

        combxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combxTipoActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Extras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 1, 12), new java.awt.Color(255, 102, 0))); // NOI18N

        cbxQueso.setText("Queso");
        cbxQueso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickSobreExtras(evt);
            }
        });

        cboxPina.setText("Piña");
        cboxPina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickSobreExtras(evt);
            }
        });

        cbxAceitunas.setText("Aceitunas");
        cbxAceitunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickSobreExtras(evt);
            }
        });

        cbxChampinones.setText("Champiñones");
        cbxChampinones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickSobreExtras(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(cbxQueso)
                .addGap(18, 18, 18)
                .addComponent(cboxPina)
                .addGap(40, 40, 40)
                .addComponent(cbxAceitunas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxChampinones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxQueso)
                    .addComponent(cboxPina)
                    .addComponent(cbxAceitunas)
                    .addComponent(cbxChampinones)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nota ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 1, 12), new java.awt.Color(204, 102, 0))); // NOI18N

        taNota.setColumns(20);
        taNota.setRows(5);
        jScrollPane1.setViewportView(taNota);

        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnImprimir.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCreditos.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnCreditos.setText("Créditos");
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreditos)))
                .addContainerGap())
        );

        lblCosto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCosto.setForeground(new java.awt.Color(153, 0, 0));

        lbl_fotoPizza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(combxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbl_fotoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_fotoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        jTabbedPane1.addTab("Preparación de pedidos", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        tabPedidos.setFont(new java.awt.Font("Corbel", 0, 10)); // NOI18N
        tabPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Tamaño", "Queso", "Piña", "Aceitunas", "Champiñon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPedidosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabPedidos);

        taNotaReconstruida.setColumns(20);
        taNotaReconstruida.setRows(5);
        jScrollPane3.setViewportView(taNotaReconstruida);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listas de pedidos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combxTipoActionPerformed
        switch(combxTipo.getSelectedIndex()){
            case 0:  lbl_fotoPizza.setIcon(icPepperoni); break;
            case 1:  lbl_fotoPizza.setIcon(icHawaiana); break;
            case 2:  lbl_fotoPizza.setIcon(icMexicana); break;
            case 3:  lbl_fotoPizza.setIcon(icItaliana); break;
            case 4:  lbl_fotoPizza.setIcon(ic4Quesos); break;
        }
        calcularPrecio();
    }//GEN-LAST:event_combxTipoActionPerformed

    private void rbMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMedianaActionPerformed
        //calcularPrecio(a+10);
    }//GEN-LAST:event_rbMedianaActionPerformed

    private void clickRadioBotonTamano(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickRadioBotonTamano
        calcularPrecio();        
    }//GEN-LAST:event_clickRadioBotonTamano

    private void clickSobreExtras(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickSobreExtras
        calcularPrecio();
    }//GEN-LAST:event_clickSobreExtras

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try {
            taNota.print();
        } catch (PrinterException ex) {
            Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        JFileChooser browser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto","txt");
        browser.setFileFilter(filtro);
        int resultado = browser.showSaveDialog(null);
        if(resultado == JFileChooser.APPROVE_OPTION){
            String arch = browser.getSelectedFile().getAbsolutePath()+".txt";
            String nota = taNota.getText();
            String mensaje = "grabado exitoso";
            FileWriter writer = null;
            try {
                writer = new FileWriter(arch);
                BufferedWriter buffer = new BufferedWriter(writer);
                buffer.write(nota);
                buffer.close();
            } catch (IOException ex) {
                mensaje = "error al grabar";
                Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    writer.close();
                    JOptionPane.showMessageDialog(rootPane, mensaje);
                } catch (IOException ex) {
                    Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        switch(combxTipo.getSelectedIndex()){
            case 0: tabPedidos.setValueAt("Pepperoni", crenglon, 0); break;
            case 1: tabPedidos.setValueAt("Hawaiana", crenglon, 0); break;
            case 2: tabPedidos.setValueAt("Mexicana", crenglon, 0); break;
            case 3: tabPedidos.setValueAt("Italiana", crenglon, 0); break;
            case 4: tabPedidos.setValueAt("4 Quesos", crenglon, 0); break;
        }
        if(rbChica.isSelected()) tabPedidos.setValueAt("Chica", crenglon, 1);
        if(rbMediana.isSelected()) tabPedidos.setValueAt("Mediana", crenglon, 1);
        if(rbGrande.isSelected()) tabPedidos.setValueAt("Grande", crenglon, 1);
        if(rbJumbo.isSelected()) tabPedidos.setValueAt("Jumbo", crenglon, 1);        

        if(cbxQueso.isSelected()) tabPedidos.setValueAt("Si", crenglon, 2);
        if(cboxPina.isSelected()) tabPedidos.setValueAt("Si", crenglon, 3);
        if(cbxAceitunas.isSelected()) tabPedidos.setValueAt("Si", crenglon, 4);
        if(cbxChampinones.isSelected()) tabPedidos.setValueAt("Si", crenglon, 5);
        
        crenglon++;
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void tabPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPedidosMouseClicked
        int r = tabPedidos.getSelectedRow();
        String tipo = (String) tabPedidos.getValueAt(r, 0);
        String tam = (String) tabPedidos.getValueAt(r, 1);
        String queso = (String) tabPedidos.getValueAt(r, 2);
        String pina = (String) tabPedidos.getValueAt(r, 3);
        String aceit = (String) tabPedidos.getValueAt(r, 4);
        String cham = (String) tabPedidos.getValueAt(r, 5);
        
        taNotaReconstruida.setText("Pizzeria \"EL POLLO\" \n\n");
        taNotaReconstruida.append("Tipo: "+ tipo);
        taNotaReconstruida.append("\nTamaño: "+tam);
        if(queso != null || pina != null || aceit !=null || cham != null)
            taNotaReconstruida.append("\nExtras: ");
        if(queso != null) taNotaReconstruida.append("\n- Queso ");
        if(pina != null) taNotaReconstruida.append("\n- Piña ");
        if(aceit != null) taNotaReconstruida.append("\n- Aceitunas ");
        if(cham != null) taNotaReconstruida.append("\n- Champiñones ");
    }//GEN-LAST:event_tabPedidosMouseClicked

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        acerca.setTitle("Acerca de...");
        acerca.setResizable(false);
        acerca.setLocationRelativeTo(null);
        acerca.setVisible(true);
    }//GEN-LAST:event_btnCreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup buttonGroupTamaños;
    private javax.swing.JCheckBox cboxPina;
    private javax.swing.JCheckBox cbxAceitunas;
    private javax.swing.JCheckBox cbxChampinones;
    private javax.swing.JCheckBox cbxQueso;
    private javax.swing.JComboBox<String> combxTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lbl_fotoPizza;
    private javax.swing.JRadioButton rbChica;
    private javax.swing.JRadioButton rbGrande;
    private javax.swing.JRadioButton rbJumbo;
    private javax.swing.JRadioButton rbMediana;
    private javax.swing.JTextArea taNota;
    private javax.swing.JTextArea taNotaReconstruida;
    private javax.swing.JTable tabPedidos;
    // End of variables declaration//GEN-END:variables
}
